const data = {
  products:  [
        {
           _id: 1,
           name: 'Nike Mens Slim Shirts',
           category: 'Mens Casual Fashion Long Sleeve Shirt',
           image: './images/5K.jpg_300x300.jpg',
           price: 120,
           brand: 'Nike',
           rating: 4.5,
           numReViews: 10,
           description: 'high quality product',
        },
        {
            _id: 2,
            name: 'Slim Washed Shirts',
            category: 'Fashion Slim Washed Designer Shirts for Men',
            image: './images/Fashion Slim Washed Designer Shirts for Men.jpg',
            price: 100,
            brand: 'Nike',
            rating: 4.5,
            numReViews: 10,
            description: 'high quality product',
         },
         {
            _id: 3,
            name: 'Fashion Slim Shirts',
            category: 'Mens Casual Fashion Long Sleeve Shirt',
            image: './images/Fashion Slim Shirts for Men.jpeg',
            price: 120,
            brand: 'Adidas',
            rating: 4.5,
            numReViews: 10,
            description: 'high quality product',
         },
         {
            _id: 4,
            name: 'Slim Style Shirts',
            category: 'Mens Casual Fashion Long Sleeve Shirt',
            image: './images/fashion slim style shirts for man.jpg',
            price: 99.5,
            brand: 'Lacoste',
            rating: 4.5,
            numReViews: 10,
            description: 'high quality product',
         },
         {
            _id: 5,
            name: 'Designer Shirt for Men',
            category: 'Slim Washed Designer Shirts for Men',
            image: './images/Fashion Slim Washed Designer Shirts for Men.jpg',
            price: 99,
            brand: 'Nike',
            rating: 4.5,
            numReViews: 10,
            description: 'high quality product',
         },
         {
             _id: 6,
             name: 'Designer Shirt for Men',
             category: 'Mens Casual Fashion Long Sleeve Shirt',
             image: "./images/Men's Shirts,Fashion Men's.png",
             price: 100,
             brand: 'Puma',
             rating: 4.5,
             numReViews: 10,
             description: 'high quality product',
          },
          {
             _id: 7,
             name: 'Designer Shirt for Men',
             category: 'Mens Casual Fashion Long Sleeve Shirt',
             image: './images/mens Shirts.jpg',
             price: 110,
             brand: 'Nike',
             rating: 4.5,
             numReViews: 10,
             description: 'high quality product',
          },
          {
             _id: 8,
             name: 'Nike Slim Shirts',
             category: 'Mens Casual Fashion Long Sleeve Shirt',
             image: './images/H049edfe06a6a4bdabfebdc0b82a3f2f58.jpg',
             price: 105,
             brand: 'Nike',
             rating: 4.5,
             numReViews: 10,
             description: 'high quality product',
          },
          {
            _id: 9,
            name: 'Nike Mens Slim Shirts',
            category: 'Mens Casual Fashion Long Sleeve Shirt',
            image: './images/ff7edb9d6aab5ce36a77dac8a9ed8102L.jpg',
            price: 99,
            brand: 'Nike',
            rating: 4.5,
            numReViews: 10,
            description: 'high quality product',
         },
        ],
};
export default data;